# Change these first
owner: AgathonLi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Komari
    url: https://status.uuui.uk
  - name: Nezha
    url: https://status.990910.xyz
  - name: SnappyMail
    url: https://mail.uuui.uk
  - name: CloudMail
    url: https://mail.river-z.de
  - name: Cloudreve
    url: https://sto.river-z.de
  - name: EasyImage
    url: https://pic-da.990910.xyz
  - name: Lsky Pro
    url: https://pickr.211118.xyz
  - name: MetaTube
    url: https://ko0327-agathonli.koyeb.app
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.uuui.uk
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/AgathonLi/upptime/raw/refs/heads/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/AgathonLi/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
